### ISSUE TITLE
published version doesn't work

### ISSUE THREAD

**Issue by Art3mK** [kcl-lang/crossplane-kcl#3]
Hey 👋

Thanks for the interesting function!  

### What happened?

Looks like there are no published function, which I can try? Not sure if that's docker image problem or my local machine setup. And I'm not sure how to list versions available.

So I'm trying to run `examples/resources/loop` with `functions.yaml` changed to:
```yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: kcl-function
spec:
  package: kcllang/crossplane-kcl
```

which IIUC should run function in docker image, pulled from somewhere? 🤔 

but all I get is:

```
➜  loop git:(main) make run
crossplane beta render xr.yaml composition.yaml functions.yaml -r
crossplane: error: cannot render composite resource: cannot start Function "kcl-function": cannot start Docker container: Error response from daemon: unable to find user nonroot: no matching entries in passwd file
```

I'm running on arm64 macos with docker desktop

Thanks!
